feature/firebase-login-operations
alicimen0614/asset_tracker pull request #3
Opened 2024-12-18 14:54 UTC by alicimen0614

2024-12-19 00:40 UTC, TrSaka approved these changes

2024-12-19 10:01 UTC, E-MRE requested changes
auth service konusu önemli

2024-12-21 11:19 UTC, E-MRE requested changes
eline sağlık

2024-12-21 11:19 UTC, E-MRE commented on lib/core/state/auth_notifier.dart
> +    state = state.copyWith(isLoading: true, error: null);
null yazmaya gerek yok

2024-12-21 11:19 UTC, E-MRE commented on lib/core/utils/enums/auth_error_enum.dart
> +  static AuthError fromFirebaseError(FirebaseAuthException exception) {
final error = exception.code.toAuthError();

extension AuthErrorExtension on String {
AuthError toAuthError(){
  switch (this) {
      case 'invalid-email':
        return AuthError.invalidEmail;
      case 'user-disabled':
        return AuthError.userDisabled;
      case 'user-not-found':
        return AuthError.userNotFound;
      case 'wrong-password':
        return AuthError.wrongPassword;
      case 'too-many-requests':
        return AuthError.tooManyRequests;
      case 'email-already-in-use':
        return AuthError.emailAlreadyInUse;
      case 'operation-not-allowed':
        return AuthError.operationNotAllowed;
      case 'weak-password':
        return AuthError.weakPassword;
      default:
        return AuthError.unknown;
    }
  }

2025-01-05 22:08 UTC, TrSaka commented on lib/providers/providers.dart
> +  return FirebaseAuthService(FirebaseAuth.instance);
Hocam bunun daha üst bir class ı yoksa bunu direkt instance olarak verebilirsin

final _firebaseAuthService = FirebaseAuthService(FirebaseAuth.instance);
tarzında bir daha ref.watch() etmene gerek kalmaz

2025-01-06 08:13 UTC, E-MRE approved these changes
eline sağlık

2025-01-06 08:45 UTC, alicimen0614 commented on lib/providers/providers.dart
> +  return FirebaseAuthService(FirebaseAuth.instance);
Teşekkür ederim enes tekrar düzelttim.

2025-01-06 08:46 UTC, merged